# Numpy
Numpy is a python library to create multidimensional array for scientifice and numerical computing.

In [1]:
import numpy as np

### Initialize Array:

In [2]:
#1D Array:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
#2D Array:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


### Get Dimensions:

In [5]:
a.ndim

1

In [6]:
b.ndim

2

### Get Shape:

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

### Get Data Type:

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype #4 Byte

dtype('int32')

### Get Size:

In [11]:
a.itemsize

4

In [12]:
b.itemsize

4

### Get Total Size:

In [13]:
a.size

3

In [14]:
b.size

6

### Initializing Array for Specific Data Type:

In [15]:
c = np.array([1,2,3,4,5,6,7,8,9], dtype = 'int16') #2 byte
c.dtype

dtype('int16')

### To Fetch a Complete Row: (Using Indexing)

In [16]:
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
b[0, :]

array([1, 2, 3])

### To Fetch a Complete Column:

In [18]:
b[:, 1]

array([2, 5])

### To Fetch a Specific Element:

In [19]:
b[1,0]

4

### [Startindex:Endindex:Stepsize]

In [20]:
b[0,0:2:1]

array([1, 2])

In [21]:
b[1,0:3:1]

array([4, 5, 6])

In [22]:
b[1,0:3:2]

array([4, 6])

### Changing Particular Element in an Array:

In [23]:
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
b[0,2] = 20
print(b)

[[ 1  2 20]
 [ 4  5  6]]


In [25]:
b[:,1] = 9
print(b)

[[ 1  9 20]
 [ 4  9  6]]


### Initializing 3D Array:

In [26]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
d[:,1,1]

array([4, 8])

In [28]:
d[0,1,0]

3

In [29]:
d[0,:,:]

array([[1, 2],
       [3, 4]])

### Initializing All Zero Matrix:

In [30]:
# 1D Array:
p = np.zeros(5)
print(p)

[0. 0. 0. 0. 0.]


In [31]:
p.dtype

dtype('float64')

In [32]:
p = np.zeros(5, dtype = 'int32')
print(p)

[0 0 0 0 0]


In [33]:
p.dtype

dtype('int32')

In [34]:
# 2D Array:
q = np.zeros((2,3), dtype='int32')
print(q)

[[0 0 0]
 [0 0 0]]


### Initializing All One's Matrix:

In [35]:
r = np.ones(6)
print(r)

[1. 1. 1. 1. 1. 1.]


In [36]:
s = np.ones((4,2,2), dtype='int16')
print(s)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


### Initializing a Matrix of Any Other Number:

In [37]:
t = np.full((2,2),99)
print(t)

[[99 99]
 [99 99]]


In [38]:
t.dtype

dtype('int32')

In [39]:
u = np.full((2,2),99.8)
print(u)

[[99.8 99.8]
 [99.8 99.8]]


In [40]:
u.dtype

dtype('float64')

### Initializing a Matrix of Any Other Number: (full_like)

In [41]:
print(c)

[1 2 3 4 5 6 7 8 9]


In [42]:
np.full_like(c, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int16)

In [43]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
np.full_like(d, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

### Matrix of Random Decimal Number:

In [45]:
x = np.random.rand(4,2)
print(x)

[[0.95357966 0.65915133]
 [0.24425442 0.65893296]
 [0.92082914 0.14851736]
 [0.34189162 0.81243698]]


### Matrix of Random Decimal Number with Shape:

In [46]:
y = np.random.random_sample(c.shape)
print(y)

[0.25542121 0.03287345 0.58073736 0.62718592 0.25230217 0.03107527
 0.28560285 0.78665051 0.74980598]


In [47]:
z = np.random.random_sample(d.shape)
print(z)

[[[0.67371057 0.65584673]
  [0.80108289 0.97477344]]

 [[0.8967075  0.4377963 ]
  [0.49222744 0.40677258]]]


### Matrix of Random Integer Number:

In [48]:
rand_int = np.random.randint(7, size = (3,3))
print(rand_int)

[[4 1 4]
 [0 3 2]
 [6 4 1]]


In [49]:
rand_inte = np.random.randint(4, 7, size = (3,3))
print(rand_inte)

[[4 6 4]
 [6 5 4]
 [4 6 5]]


### Indentity Matrix:

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeating Array:

In [52]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
re_arr1 = np.repeat(arr, 3, axis = 0)
print(re_arr1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [54]:
re_arr2 = np.repeat(arr, 3, axis = 1)
print(re_arr2)

[[1 1 1 2 2 2 3 3 3 4 4 4]
 [5 5 5 6 6 6 7 7 7 8 8 8]]


### Task:

In [55]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
zer = np.zeros((3,3))
print(zer)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
zer[1,1] = 9
print(zer)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [58]:
output[1:4,1:4] = zer
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying Matrix:

In [59]:
a_cop = np.array([1,2,3])
print(a_cop)

[1 2 3]


In [60]:
# Improper Way:
b_cop = a_cop
print(b_cop)

[1 2 3]


In [61]:
b_cop[0] = 100
print(b_cop)

[100   2   3]


In [62]:
print(a_cop)

[100   2   3]


In [63]:
# Proper Way:
a_cop = np.array([1,2,3])
print(a_cop)

[1 2 3]


In [64]:
b_cop = a_cop.copy()
print(b_cop)

[1 2 3]


In [65]:
b_cop[0] = 100
print(b_cop)

[100   2   3]


In [66]:
print(a_cop)

[1 2 3]


### Mathematical Form:

In [67]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [68]:
a+2

array([3, 4, 5, 6])

In [69]:
a-2

array([-1,  0,  1,  2])

In [70]:
a*2

array([2, 4, 6, 8])

In [71]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [72]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [73]:
a+b

array([ 6,  8, 10, 12])

In [74]:
a*b

array([ 5, 12, 21, 32])

In [75]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

### Linear Algebra:

In [77]:
a = np.ones([2,3], dtype = 'int16')
print(a)

[[1 1 1]
 [1 1 1]]


In [78]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [79]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

### Sats:

In [80]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [81]:
np.min(a)

1

In [82]:
np.max(a)

6

In [83]:
np.min(a, axis=0) #min index value of a row

array([1, 2, 3])

In [84]:
np.min(a, axis=1) #min index value of a column

array([1, 4])

In [85]:
np.max(a, axis=1)

array([3, 6])

### Reorganizing Matrix:

In [86]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [87]:
after = before.reshape(6,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [88]:
after = before.reshape(1,6)
print(after)

[[1 2 3 4 5 6]]


### Stacking Vectors:

In [89]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [90]:
# Vertical Stacking:
np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [91]:
# Horizontal Stacking:
np.hstack([v1,v2,v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

### Indexing:

In [92]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [93]:
a[[1,2,8]] #all are index numbers

array([2, 3, 9])